max_release_time_secs: 20
offset_seconds: 600
release_time_secs: 1
popup_parameters:
- date: 2024/11/15 16:00:00
  gpio: 12
  id: 1
  releaseMode: DM
  released: false
  sleeptime_h: '24'
  sleeptime_m: '0'
- date: 2025/10/31 09:00:00
  gpio: 11
  id: 2
  releaseMode: FRM
  released: false
  sleeptime_h: '24'
  sleeptime_m: '0'
- date: 2024/11/04 09:00:00
  gpio: 10
  id: 3
  releaseMode: FRM
  released: false
  sleeptime_h: '24'
  sleeptime_m: '0'

